### ISSUE TITLE
Ordering broken after recent Maul update

### ISSUE THREAD

**Issue by astradurs** [jbbjarnason/maul-replica#4]
In a very recent (today-ish) update to the Maul API and the Maul website the menu went through some changes. I am listing the changes made as an effort of due diligence since our intention was not to shut out tools like this one.

The menu itself was flattened (it used to be a 2DArray) and each item of the array now holds a **WeekdayNumber** Attribute instead.
New Attributes were added: 
- **DietTypes** [array of strings], to support multiple diets on a menuItem
- **Allergens** [array of strings], I do not think this one needs explaining
- **AllergensProvided** [boolean], flag courses from restaurants that have not provided us with any detail on their allergens
These are required on ordering. 

**Diet** still exists as an Attribute and is currently required although we might drop it in the near future.
I think an update with these changes in mind will get everything working again.

**Comment by jbbjarnason** [comment]
@astradurs  Thanks for letting know so quickly beforehand!

I think with the new changes to the frontend on maul's part makes this frontend unnecessary, the reason for making this frontend was to display all menu items without restrictions.

Maybe @aee11 will be able to verify next week?

**Comment by astradurs** [comment]
Great stuff! Let me know if there is anything that you might need.

**Comment by aee11** [comment]
@astradurs, thanks for the heads up. I made changes according to your comment and it works perfectly.
